# Leverage 14.04 LTS, same as Vagrant
sudo: required
dist: trusty

# Set our language to generic for a minimal setup
# https://docs.travis-ci.com/user/trusty-ci-environment#Image-differences-from-Precise
language: generic

before_install:
  # Debug bundler and installed gems
  - gem list
  - dpkg --list | grep bundle

  # Install bundler for the root user
  - sudo gem install bundler

  # Output OS information
  - ruby --version
  - bundle --version
  - sudo bundle --version

install:
  # Install repo specific dependencies
  - bundle install
  - ls vendor
  - git diff

script:
  # Run our provisioner
  - bin/bootstrap-travis-ci.sh

  # Run Travis tests
  - bin/test-travis-ci.sh

# Only receive notifications on the start of a new branch and when it changes status
notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
