# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Set our box as Ubuntu@14.04 LTS
  # https://atlas.hashicorp.com/ubuntu/boxes/trusty64
  config.vm.box = "ubuntu/trusty64"

  # Give additional memory and CPU to VirtualBox provider
  # https://docs.vagrantup.com/v2/virtualbox/configuration.html
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # Provision our box with a script
  # TODO: When Vagrant@1.8 is on `apt`, then move back to `path` and `env`
  config.vm.define("twolfson.com", :primary => true) do |subconfig|
    node_type = "twolfson.com"
    subconfig.vm.provision("shell", :inline => "cd /vagrant && NODE_TYPE=\"#{node_type}\" bin/bootstrap-vagrant.sh")
  end

  config.vm.define("gifsockets.twolfson.com", :autostart => false) do |subconfig|
    node_type = "gifsockets.twolfson.com"
    subconfig.vm.provision("shell", :inline => "cd /vagrant && NODE_TYPE=\"#{node_type}\" bin/bootstrap-vagrant.sh")
  end
end
